function R = eulerrotation(phi, theta, psi)
    R = [(cos(phi)*cos(theta)*cos(psi)) - (sin(phi)*sin(psi)),  -(cos(phi)*cos(theta)*sin(psi)) - (sin(phi)*cos(psi)), cos(phi)*sin(theta);...
         (sin(phi)*cos(theta)*cos(psi)) + (cos(phi)*sin(psi)),  -(sin(phi)*cos(theta)*sin(psi)) + (cos(phi)*cos(psi)), sin(phi)*sin(theta);...
          -sin(theta)*cos(psi)                               ,  sin(theta)*sin(psi)                                  , cos(theta)];
end